version: '3.8'

services:
  app:
    #image: 1c463ce82253
    build:
      context: ./NeuralNetwork
      dockerfile: dockerfile
    container_name: dockerNN
    ports:
      - 8888:5001
    volumes:
      - ./NeuralNetwork:/app
      - ./Web/dist/assets/img:/app/img
    depends_on:
      - web
    environment:
      - TZ=Asia/Taipei
    networks:
      - mynetwork
  
  web:
    #image: cf47749380ab
    build:
      context: ./Web
      dockerfile: dockerfile
    container_name: dockerWeb
    ports:
      - 3333:3000
    volumes:
      - ./Web:/web
    environment:
      - TZ=Asia/Taipei  
    networks:
      - mynetwork

  mysql:
    image: mysql
    container_name: mysql-latest
    ports:
      - 3306:3306
    volumes:
      - ./MySql/custom:/etc/mysql/conf.d
      - ./MySql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${root_password}
      - TZ=Asia/Taipei
    networks:
      - mynetwork

  cron:
    build:
      context: ./crontab
      dockerfile: dockerfile
    container_name: cronjobs
    environment:
      - TZ=Asia/Taipei
    restart: unless-stopped
    networks:
      - mynetwork

networks:
  mynetwork:
    name: my-network